[Desktop Entry]
Type=Service
Exec=blubb
Icon=text-xml
Name=DTD/Schema Catalog user interface
Name[bs]=DTD / Schema Katalog korisnički interfejs
Name[ca]=Interfície d'usuari del catàleg DTD/esquema
Name[ca@valencia]=Interfície d'usuari del catàleg DTD/esquema
Name[de]=Benutzeroberfläche für DTD/Schema-Katalog
Name[es]=Interfaz de usuario de catálogo de DTD/esquema
Name[et]=DTD/skeemi kataloogi kasutajaliides
Name[fr]=Interface utilisateur de catalogue DTD / schéma
Name[gl]=Interface de usuario de catálogo DTD ou esquema
Name[hu]=DTD/séma katalógus felhasználói felület
Name[it]=Interfaccia utente catalogo o schema DTD
Name[nl]=Gebruikersinterface voor DTD/Schema-catalogus
Name[pl]=Interfejs użytkownika DTD/Katalogu schematu
Name[pt]=Interface de utilizador para catálogos DTD/esquemas
Name[pt_BR]=Interface do usuário para catálogo de DTD/Esquemas
Name[sk]=Používateľské rozhranie katalógu DTD/schémy
Name[sv]=Användargränssnitt för DTD eller Schema-katalog
Name[tr]=DTD/Şema Kataloğu kullanıcı arayüzü
Name[uk]=Інтерфейс каталогу DTD/Schema
Name[x-test]=xxDTD/Schema Catalog user interfacexx
GenericName=XML catalog user interface
GenericName[bs]=XML  katalog korsinicki interfejs
GenericName[ca]=Interfície d'usuari del catàleg XML
GenericName[ca@valencia]=Interfície d'usuari del catàleg XML
GenericName[de]=Benutzeroberfläche für XML-Katalog
GenericName[es]=Interfaz de usuario de catálogo XML
GenericName[et]=XML-kataloogi kasutajaliides
GenericName[fr]=Interface utilisateur de catalogue XML
GenericName[gl]=Interface de usuario de catálogo XML
GenericName[hu]=XML katalógus felhasználói felület
GenericName[nl]=Gebruikersinterface voor XML-catalogus
GenericName[pl]=Interfejs użytkownika katalogu XML
GenericName[pt]=Interface de utilizador de catálogos de XML
GenericName[pt_BR]=Interface do usuário para catálogo XML
GenericName[sk]=Používateľské rozhranie katalógu XML
GenericName[sv]=Användargränssnitt för XML-katalog
GenericName[tr]=XML katalog kullanıcı arayüzü
GenericName[uk]=Інтерфейс користувача до каталогу XML
GenericName[x-test]=xxXML catalog user interfacexx
Comment=User interface to manage XML schemata and DTD documents
Comment[bs]=Korisnicki interfejs upravljaju XML shema i DTD dokumenata
Comment[ca]=Interfície d'usuari per a gestionar esquemes en XML i documents DTD
Comment[ca@valencia]=Interfície d'usuari per a gestionar esquemes en XML i documents DTD
Comment[de]=Benutzeroberfläche zur Verwaltung von XML-Schemata und DTD-Dokumenten
Comment[es]=Interfaz de usuario para gestionar esquemas XML y documentos DTD
Comment[et]=XML-skeemide ja DTD dokumentide haldamise kasutajaliides
Comment[fr]=Interface utilisateur pour gérer les « schemata » XML et les documents de DTD
Comment[gl]=Interface de usuario para xestionar esquemas de XML e documentos DTD.
Comment[hu]=Felhasználói felület XML sémák és DTD dokumentumok kezeléséhez
Comment[it]=Interfaccia utente per gestire gli schemi XML e DTD dei documenti
Comment[nl]=Gebruikersinterface voor beheer van XML schemata en DTD documenten
Comment[pl]=Interfejs użytkownika do zarządzania schematami XML i dokumentami DTD
Comment[pt]=Interface do utilizador para gerir esquemas em XML e documentos DTD
Comment[pt_BR]=Interface do usuário para gerenciar esquemas XML e documentos DTD
Comment[sk]=Používateľské rozhranie na správu XML schém a dokumentov DTD
Comment[sv]=Användargränssnitt för att hantera XML-scheman och DTD-dokument
Comment[tr]=XML şemalarını ve DTD belgeleri yönetmek için kullanıcı arabirimi
Comment[uk]=Інтерфейс користувача для керування схемами XML та документами DTD
Comment[x-test]=xxUser interface to manage XML schemata and DTD documentsxx
ServiceTypes=KDevelop/Plugin
X-KDE-Library=kdevxmlcatalogui
X-KDE-PluginInfo-Name=kdevxmlcatalogui
X-KDE-PluginInfo-Author=Ruan Strydom
X-KDE-PluginInfo-License=LGPL
X-KDevelop-Version=@KDEV_PLUGIN_VERSION@
X-KDevelop-Language=XML
X-KDevelop-Category=Global
X-KDevelop-Mode=GUI
